Repository aureuserp/aureuserp, pull requests merged in 2025-09, with the labels that each got.

#560 Issue #550 has been fixed.
  plugins/webkul/products/src/Filament/Resources/ProductResource.php
Labels: QA PASSED, Done

#565 Issue #540 has been fixed.
  plugins/webkul/accounts/src/Filament/Resources/InvoiceResource.php
Labels: QA PASSED

#566 issue #542 has been fixed.
  plugins/webkul/website/resources/views/filament/customer/header/auth-links.blade.php
Labels: QA PASSED

#567 Issue #539 has been fixed.
  plugins/webkul/products/src/Filament/Resources/ProductResource.php
Labels: QA PASSED, Done

#568 Issue #533 has been fixed.
  .env.example
  config/app.php
  plugins/webkul/purchases/src/Filament/Admin/Clusters/Orders/Resources/OrderResource.php
  plugins/webkul/purchases/src/Livewire/Summary.php
  plugins/webkul/security/src/Filament/Resources/UserResource.php
  plugins/webkul/support/src/helpers.php
Labels: QA PASSED, Done

#529 FIxed delivery order creation issue durin sale order confirmation
  plugins/webkul/sales/src/SaleManager.php
Labels: QA PASSED

#572 Issue #511 has been fixed.
  plugins/webkul/website/src/Filament/Admin/Resources/PageResource/Pages/EditPage.php
  plugins/webkul/website/src/WebsitePlugin.php
Labels: QA PASSED, Done

#573 Issue #509 has been fixed.
  plugins/webkul/support/src/Filament/Resources/ActivityTypeResource.php
  plugins/webkul/support/src/Filament/Resources/ActivityTypeResource/Pages/ListActivityTypes.php
  plugins/webkul/time-off/src/Filament/Clusters/Configurations/Resources/ActivityTypeResource.php
  plugins/webkul/time-off/src/Filament/Clusters/Configurations/Resources/ActivityTypeResource/Pages/CreateActivityType.php
  plugins/webkul/time-off/src/Filament/Clusters/Configurations/Resources/ActivityTypeResource/Pages/EditActivityType.php
  plugins/webkul/time-off/src/Filament/Clusters/Configurations/Resources/ActivityTypeResource/Pages/ListActivityTypes.php
Labels: QA PASSED

#576 Issue #502 has been fixed.
  plugins/webkul/time-off/src/Enums/CarryoverDay.php
  plugins/webkul/time-off/src/Filament/Clusters/Configurations/Resources/AccrualPlanResource.php
  plugins/webkul/time-off/src/Filament/Clusters/Configurations/Resources/AccrualPlanResource/Pages/CreateAccrualPlan.php
  plugins/webkul/time-off/src/Filament/Clusters/Configurations/Resources/AccrualPlanResource/Pages/EditAccrualPlan.php
  plugins/webkul/time-off/src/Filament/Clusters/Configurations/Resources/AccrualPlanResource/Pages/ManageMilestone.php
  plugins/webkul/time-off/src/Filament/Clusters/Configurations/Resources/AccrualPlanResource/Pages/ViewAccrualPlan.php
  plugins/webkul/time-off/src/Models/LeaveAccrualPlan.php
Labels: QA PASSED, Done

#577 Issue #501 has been fixed.
  plugins/webkul/time-off/resources/lang/en/filament/widgets/calendar-widget.php
  plugins/webkul/time-off/src/Filament/Clusters/MyTime/Resources/MyAllocationResource.php
  plugins/webkul/time-off/src/Filament/Clusters/MyTime/Resources/MyTimeOffResource.php
  plugins/webkul/time-off/src/Filament/Pages/Dashboard.php
  plugins/webkul/time-off/src/Filament/Widgets/CalendarWidget.php
  plugins/webkul/time-off/src/TimeOffServiceProvider.php
Labels: QA PASSED

#578 Issue #500 has been fixed.
  plugins/webkul/employees/src/Models/EmployeeJobPosition.php
Labels: QA PASSED

#586 Issue #491 has been fixed.
  plugins/webkul/projects/src/Filament/Resources/ProjectResource.php
Labels: QA PASSED

#590 Issue #480 has been fixed.
  plugins/webkul/sales/src/Filament/Clusters/Orders/Resources/QuotationResource.php
Labels: QA PASSED

#594 Issue #473 has been fixed.
  plugins/webkul/inventories/src/Filament/Clusters/Operations/Resources/OperationResource.php
Labels: QA PASSED, Done

#595 Clean Up Redundant deadline Cast Definition – Ref #467
  plugins/webkul/projects/src/Models/Task.php
Labels: QA PASSED

#597 Issue #462 has been fixed.
  plugins/webkul/sales/src/Filament/Clusters/Orders/Resources/QuotationResource.php
Labels: QA PASSED

#598 Issue #457 has been fixed.
  plugins/webkul/accounts/src/Filament/Resources/TaxResource.php
Labels: QA PASSED

#606 Issue #603 has been fixed.
  plugins/webkul/purchases/resources/lang/en/filament/admin/clusters/orders/resources/quotation.php
  plugins/webkul/purchases/resources/lang/en/filament/admin/clusters/orders/resources/quotation/pages/list-quotation.php
  plugins/webkul/purchases/src/Filament/Admin/Clusters/Orders/Resources/QuotationResource/Pages/ListQuotations.php
Labels: QA PASSED, Done

#611 Issue #602 has been fixed.
  plugins/webkul/accounts/src/Filament/Resources/TaxGroupResource.php
Labels: QA PASSED

#616 Issue #608 has been fixed.
  plugins/webkul/accounts/database/migrations/2025_08_01_091957_alter_accounts_payment_terms_table.php
  plugins/webkul/accounts/src/AccountServiceProvider.php
Labels: QA PASSED, Done

#624 Issue #538 has been fixed.
  plugins/webkul/invoices/src/Filament/Clusters/Vendors/Resources/VendorResource/Pages/CreateVendor.php
  plugins/webkul/invoices/src/Filament/Clusters/Vendors/Resources/VendorResource/Pages/EditVendor.php
  plugins/webkul/invoices/src/Filament/Clusters/Vendors/Resources/VendorResource/Pages/ListVendors.php
  plugins/webkul/invoices/src/Filament/Clusters/Vendors/Resources/VendorResource/Pages/ManageAddresses.php
  plugins/webkul/invoices/src/Filament/Clusters/Vendors/Resources/VendorResource/Pages/ManageBankAccounts.php
  plugins/webkul/invoices/src/Filament/Clusters/Vendors/Resources/VendorResource/Pages/ManageContacts.php
  plugins/webkul/invoices/src/Filament/Clusters/Vendors/Resources/VendorResource/Pages/ViewVendor.php
Labels: QA PASSED

#626 Issue #618 has been fixed.
  plugins/webkul/recruitments/resources/lang/en/filament/clusters/applications/resources/candidate.php
Labels: QA PASSED, Done

#630 Issue #546 has been fixed.
  plugins/webkul/invoices/src/Filament/Clusters/Customer/Resources/PartnerResource/Pages/ManageBankAccounts.php
  plugins/webkul/partners/src/Filament/Resources/BankAccountResource.php
  plugins/webkul/partners/src/Models/BankAccount.php
Labels: QA PASSED, Done

#633 Issue #461 has been fixed.
  plugins/webkul/accounts/src/AccountManager.php
Labels: QA PASSED, Done

#625 Issue #600 has been fixed.
  plugins/webkul/accounts/database/migrations/2025_08_04_062050_alter_accounts_taxes_table.php
  plugins/webkul/accounts/src/AccountServiceProvider.php
Labels: QA PASSED, Change Requested, Done

#583 Issue #495 has been fixed.
  plugins/webkul/projects/resources/lang/en/filament/clusters/configurations/resources/project-stage.php
  plugins/webkul/projects/src/Filament/Clusters/Configurations/Resources/ProjectStageResource.php
  plugins/webkul/projects/src/Models/ProjectStage.php
Labels: QA PASSED, Change Requested, Done

#589 Issue #485 has been fixed.
  plugins/webkul/purchases/resources/views/livewire/summary.blade.php
  plugins/webkul/purchases/src/Livewire/Summary.php
Labels: QA PASSED, Change Requested, Done

#599 Issue #456 has been fixed.
  plugins/webkul/time-off/resources/lang/en/filament/clusters/management/resources/time-off.php
  plugins/webkul/time-off/src/Filament/Clusters/Management/Resources/TimeOffResource.php
  plugins/webkul/time-off/src/Filament/Clusters/Management/Resources/TimeOffResource/Pages/CreateTimeOff.php
  plugins/webkul/time-off/src/Filament/Clusters/Management/Resources/TimeOffResource/Pages/EditTimeOff.php
  plugins/webkul/time-off/src/Filament/Clusters/Management/Resources/TimeOffResource/Pages/ListTimeOff.php
  plugins/webkul/time-off/src/Filament/Clusters/Reporting/Resources/ByEmployeeResource.php
  plugins/webkul/time-off/src/Filament/Clusters/Reporting/Resources/ByEmployeeResource/Pages/CreateByEmployee.php
  plugins/webkul/time-off/src/Filament/Clusters/Reporting/Resources/ByEmployeeResource/Pages/EditByEmployee.php
  plugins/webkul/time-off/src/Filament/Clusters/Reporting/Resources/ByEmployeeResource/Pages/ListByEmployees.php
  plugins/webkul/time-off/src/Filament/Clusters/Reporting/Resources/ByEmployeeResource/Pages/ViewByEmployee.php
  plugins/webkul/time-off/src/Models/Leave.php
Labels: QA PASSED, Change Requested, Done

#636 Issue #634 has been fixed.
  plugins/webkul/accounts/resources/lang/en/filament/resources/invoice.php
  plugins/webkul/accounts/src/Filament/Resources/InvoiceResource.php
Labels: QA PASSED

#638 Issue #620 has been fixed.
  plugins/webkul/sales/src/Filament/Clusters/Orders/Resources/QuotationResource/Pages/ManageDeliveries.php
Labels: QA PASSED

#647 Issue #408 has been fixed.
  plugins/webkul/accounts/database/seeders/PaymentMethodLineSeeder.php
  plugins/webkul/accounts/src/Filament/Resources/InvoiceResource/Actions/PayAction.php
  plugins/webkul/invoices/src/Models/Invoice.php
Labels: QA PASSED

#651 Issue #649 has been fixed.
  plugins/webkul/projects/resources/lang/en/filament/widgets/stats-overview.php
  plugins/webkul/projects/resources/lang/en/filament/widgets/task-by-stage.php
  plugins/webkul/projects/resources/lang/en/filament/widgets/task-by-state.php
  plugins/webkul/projects/resources/lang/en/filament/widgets/top-assignees.php
  plugins/webkul/projects/resources/lang/en/filament/widgets/top-projects.php
  plugins/webkul/projects/src/Filament/Widgets/StatsOverviewWidget.php
  plugins/webkul/projects/src/Filament/Widgets/TaskByStageChart.php
  plugins/webkul/projects/src/Filament/Widgets/TaskByStateChart.php
  plugins/webkul/projects/src/Filament/Widgets/TopAssigneesWidget.php
  plugins/webkul/projects/src/Filament/Widgets/TopProjectsWidget.php
  plugins/webkul/recruitments/resources/lang/en/filament/widgets/applicant.php
  plugins/webkul/recruitments/resources/lang/en/filament/widgets/job-position.php
  plugins/webkul/recruitments/src/Filament/Widgets/ApplicantChartWidget.php
  plugins/webkul/recruitments/src/Filament/Widgets/JobPositionStatsWidget.php
  plugins/webkul/time-off/resources/lang/en/filament/widgets/calendar-widget.php
  plugins/webkul/time-off/resources/lang/en/filament/widgets/my-time-off-widget.php
  plugins/webkul/time-off/resources/lang/en/filament/widgets/overview-calendar-widget.php
  plugins/webkul/time-off/src/Filament/Widgets/CalendarWidget.php
  plugins/webkul/time-off/src/Filament/Widgets/MyTimeOffWidget.php
  plugins/webkul/time-off/src/Filament/Widgets/OverviewCalendarWidget.php
Labels: QA PASSED

#655 add placeholder in term and conditions.
  plugins/webkul/sales/src/Filament/Clusters/Orders/Resources/QuotationResource.php
Labels: QA PASSED

#666 Issue #665 has been fixed.
  plugins/webkul/sales/src/Filament/Clusters/Orders/Resources/QuotationResource.php
Labels: QA PASSED

#668 Issue #663 has been fixed.
  plugins/webkul/inventories/src/Filament/Clusters/Configurations/Resources/RouteResource.php
Labels: QA PASSED, Done

#669 Issue #661 has been fixed.
  plugins/webkul/employees/resources/lang/en/filament/resources/department/pages/edit-department.php
  plugins/webkul/employees/src/Filament/Resources/DepartmentResource.php
  plugins/webkul/employees/src/Filament/Resources/DepartmentResource/Pages/EditDepartment.php
  plugins/webkul/employees/src/Models/Department.php
Labels: QA PASSED, Done

#674 Issue #672 has been fixed.
  plugins/webkul/employees/src/Filament/Clusters/Configurations/Resources/JobPositionResource.php
Labels: QA PASSED

#680 Issue #622 has been fixed.
  plugins/webkul/employees/resources/lang/en/filament/resources/employee.php
  plugins/webkul/employees/src/Filament/Resources/EmployeeResource.php
Labels: QA PASSED

#697 Issue #696 and #695 has been fixed.
  plugins/webkul/security/src/Filament/Resources/RoleResource.php
  plugins/webkul/security/src/Filament/Resources/RoleResource/Pages/CreateRole.php
  plugins/webkul/security/src/Filament/Resources/RoleResource/Pages/EditRole.php
Labels: QA PASSED, Done

#699 Issue #688 has been fixed.
  plugins/webkul/projects/src/Filament/Widgets/TopAssigneesWidget.php
  plugins/webkul/projects/src/Filament/Widgets/TopProjectsWidget.php
Labels: QA PASSED

#656 Feature #609 has been added
  plugins/webkul/accounts/src/Filament/Resources/InvoiceResource.php
  plugins/webkul/sales/src/Filament/Clusters/Orders/Resources/QuotationResource.php
Labels: QA PASSED, Change Requested, Done

#679 Issue #678 has been fixed.
  plugins/webkul/security/src/Filament/Resources/RoleResource.php
  plugins/webkul/security/src/Filament/Resources/RoleResource/Pages/EditRole.php
  plugins/webkul/security/src/Filament/Resources/RoleResource/Pages/ViewRole.php
Labels: QA PASSED, Change Requested, Done

#701 Issue #693 has been fixed.
  plugins/webkul/security/src/Filament/Resources/RoleResource.php
  plugins/webkul/security/src/Filament/Resources/RoleResource/Pages/CreateRole.php
  plugins/webkul/security/src/Filament/Resources/RoleResource/Pages/EditRole.php
Labels: QA PASSED, Change Requested, Done

#712 Issue #512
  plugins/webkul/blogs/database/migrations/2025_09_03_070414_alter_blogs_posts_table.php
  plugins/webkul/blogs/resources/lang/en/filament/admin/clusters/configurations/resources/category.php
  plugins/webkul/blogs/resources/views/filament/customer/resources/post/pages/list-records.blade.php
  plugins/webkul/blogs/src/BlogServiceProvider.php
  plugins/webkul/blogs/src/Filament/Admin/Clusters/Configurations/Resources/CategoryResource.php
  plugins/webkul/blogs/src/Filament/Admin/Resources/PostResource.php
  plugins/webkul/security/src/Models/User.php
  plugins/webkul/website/resources/views/filament/customer/header/auth-links.blade.php
Labels: QA PASSED

#707 New issue fixed in employee resource
  plugins/webkul/employees/src/Filament/Resources/EmployeeResource.php
Labels: QA PASSED

#719 fixed blogs plugin installation issue
  plugins/webkul/blogs/database/migrations/2025_09_03_070414_alter_blogs_posts_table.php
Labels: QA PASSED

#763 feat: enhance ERP installation command with admin user options
  .gitignore
  plugins/webkul/support/src/Console/Commands/InstallERP.php
Labels: QA PASSED

#786 remove the unused imports.
  plugins/webkul/security/src/Filament/Resources/CompanyResource.php
Labels: QA PASSED

#781 Update accept invitation translations
  plugins/webkul/security/resources/lang/en/livewire/accept-invitation.php
  plugins/webkul/security/src/Livewire/AcceptInvitation.php
Labels: QA PASSED

#775 Issue #755 has been fixed.
  plugins/webkul/support/resources/lang/en/filament/pages/profile.php
  plugins/webkul/support/src/Filament/Pages/Profile.php
  routes/web.php
Labels: QA PASSED

#785 fix double notification on Quotation mailing
  plugins/webkul/sales/resources/lang/en/filament/clusters/orders/resources/quotation/actions/send-by-email.php
  plugins/webkul/sales/src/Filament/Clusters/Orders/Resources/QuotationResource/Actions/SendByEmailAction.php
  plugins/webkul/sales/src/SaleManager.php
Labels: QA PASSED

#790 sale Invoice Creation Issue
  plugins/webkul/invoices/src/Filament/Clusters/Vendors/Resources/ProductResource.php
  plugins/webkul/sales/src/Filament/Clusters/Orders/Resources/QuotationResource/Actions/CreateInvoiceAction.php
  plugins/webkul/sales/src/Filament/Clusters/Orders/Resources/QuotationResource/Pages/ManageInvoices.php
  plugins/webkul/sales/src/SaleManager.php
  plugins/webkul/sales/src/Settings/InvoiceSettings.php
Labels: QA PASSED

#801 Added missing navigation icon in DepartmentResource
  plugins/webkul/recruitments/src/Filament/Clusters/Configurations/Resources/DepartmentResource.php
Labels: QA PASSED

#799 Fix form submission in CancelQuotationAction to enable email sending
  plugins/webkul/sales/src/Filament/Clusters/Orders/Resources/QuotationResource/Actions/CancelQuotationAction.php
Labels: QA PASSED
